### ISSUE TITLE
unexpected editor UI appearing with "collision patches" enabled during map testing

### ISSUE THREAD

**Issue by q8X** [multitheftauto/mtasa-resources#532]
**Which resource(s) have this problem?**
edtior_gui

**Describe the bug**
when the collision patches feature is enabled during map testing, the editor UI show up, this behaviour isn't supposed to be happened

**To Reproduce**
1. Enable the "collision patches" feature in the editor settings
2. Begin a full test
3. See the editor UI appearing during the test

**Expected behavior**
the editor UI shouldn't be visible during map testing with the "collision patches" feature enabled

**Screenshots**
![mta-screen_2024-07-27_19-23-23](https://github.com/user-attachments/assets/ec0cf8b0-4394-4e37-8be8-47ab62a380b0)

**Version**
- Multi Theft Auto v1.6-release-22650
- Latest MTA default resources

**Comment by jlillis** [comment]
Resolved via #533

**Comment by xLive** [comment]
@jlillis That PR actually resolved #525. It doesn't resolve this issue.

**Comment by chris1384** [comment]
> @jlillis That PR actually resolved #525. It doesn't resolve this issue.

It did solve a part of it. Whenever you enter into editor now and do a map test, the GUI works fine unless you start tampering with the option again, the reason is yet to be found.

**Comment by Dutchman101** [comment]
Reopened as per xLive's comment.
